package org.bitcoinj.protocols.fusion.models;

public enum FusionStatus {
    NOT_FUSING,
    GENERATING_COMPONENTS,
    MAKING_COMMITMENTS,
    SUBMITTING_COMMITMENTS,
    PRODUCING_BLIND_SIGNATURES,
    COVERTLY_SENDING_COMPONENTS,
    RECEIVING_ALL_COMMITMENTS,
    RECEIVING_ALL_COMPONENTS,
    SIGNING,
    COVERTLY_SENDING_SIGNATURES,
    FUSED,
    FAILED
}
